<?php
/*************************************
 * SPDX-FileCopyrightText: 2009-2020 Vtenext S.r.l. <info@vtenext.com> 
 * SPDX-License-Identifier: AGPL-3.0-only  
 ************************************/

	require_once 'include/antlr/antlr.php';
	require_once 'VTEventConditionSymbol.php';
	require_once 'VTEventCondition.php';
	require_once 'VTEventConditionParserLexer.php';
	require_once 'VTEventConditionParserParser.php';
	require_once 'VTEntityData.inc';
	require_once 'VTEntityType.inc';
	require_once 'VTEventHandler.inc';
	require_once 'VTEventsManager.inc';
	require_once 'VTEventTrigger.inc';
?>