<?php 

/* crmv@202326 */

SDK::setLanguageEntries('ALERT_ARR', 'LBL_GRAPES_SYNTAX_ERROR', [
	'it_it' => "Il codice HTML contiene degli errori di sintassi. L'errore generato dal sistema è: \"%s\". Revisiona il tuo codice e riprova.",
	'en_us' => "The HTML code contains syntax errors. The error generated by the system is: \"%s\". Please review your code and try again.",
]);

/* crmv@202705 */

$VTEP = VTEProperties::getInstance();
$VTEP->setProperty('theme.primary_colors', array());
