#!/bin/sh
# $Id: xgetpot 1166 2008-02-23 07:18:12Z tokul $
# Copyright (c) 2007 The NaSMail Project
# This file is part of NaSMail attachment_tnef plugin.
#
# This plugin is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This plugin is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# plugin; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA
#

xgettext *.php --language=PHP \
  --output=attachment_tnef.pot --default-domain=attachment_tnef \
  --add-comments --add-location

xgettext class/*.php --language=PHP -j \
  --output=attachment_tnef.pot --default-domain=attachment_tnef \
  --add-comments --add-location
